# Generated by Django 6.0 on 2026-02-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('stream', models.CharField(choices=[('IT', 'IT'), ('Marketing', 'Marketing'), ('Finance', 'Finance'), ('HR', 'HR'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('place', models.CharField(blank=True, max_length=255)),
                ('skills', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
