# Generated by Django 6.0 on 2026-03-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
