# Generated by Django 6.0 on 2026-03-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_adminlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-applied_at']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Contract', 'Contract'), ('Other', 'Other')], default='Full Time', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, help_text='Example: 3 LPA, 50k/month', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
